// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwksthynmnrmhzyjdtpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3a3N0aHlubW5ybWh6eWpkdHBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTgzMjUsImV4cCI6MjA2NDUzNDMyNX0.7GkAUWQQ2M_um1vMNev2eJ7pJDKGVopz97WUSlsli6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);