// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfnqnkzilojjufbzqpsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmbnFua3ppbG9qanVmYnpxcHNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5ODY1MjcsImV4cCI6MjA2NDU2MjUyN30.sXXv6YsGvlQIEUzk2UeArZCbNHI5VKFu8XNMEWkdvNk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);